backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('community.urls')),
    path('admin/', admin.site.urls)
]

backend/community/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

# urlpatterns = \
#     [
#         path('login', views.login),
#         path('c/<name>/', include([
#             path('', views.getCommunity),
#             path('members/', views.getCommunityMembers),
#             path('datatypes/', views.getCommunityDataTypes),
#             path('datafields/', views.getCommunityDataFields),
#             path('posts/', views.getCommunityPosts),
#         ])),
#         path('u/<username>/', include([
#             path('', views.getUser),
#         ])),
#         path('p/<url>/', include([
#             path('', views.getPost),
#         ])),
#         path('wiki', views.wiki)
#     ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = \
    [
        # todo homepage
        path('', views.index),
        path('fieldform', views.get_field_form),
        path('postfieldsform', views.get_post_fields_form),
        path('search', views.search),
        path('sparql', views.sparql_query),
        # todo community related views
        path('c/', include([
            path('', views.CommunityViews.index),
            path('new', views.CommunityViews.create),
            path('<name>/', include([
                path('', views.CommunityViews.community),
                path('search', views.CommunityViews.search),
                path('search_results', views.CommunityViews.search_results),
                path('members/', views.CommunityViews.members),
                path('datatypes/', include([
                    path('', views.CommunityViews.data_types),
                    path('new', views.DataTypeViews.create)
                ])),
                path('posts/', include([
                    path('', views.CommunityViews.posts),
                    path('new', views.PostViews.create)
                ]))
            ]))
        ])),
        # todo user related views
        path('u/', include([
            path('', views.UserViews.index),
            # todo GET loginform?, POST login
            path('login', views.UserViews.login),
            path('logout', views.UserViews.logout),
            # todo GET signupform?, POST signup
            path('signup', views.UserViews.signup),
            path('<username>/', include([
                path('', views.UserViews.user),
                path('datatypes/', views.UserViews.data_types),
                path('datatype/<id>', views.UserViews.data_type),
                path('posts/', views.UserViews.posts),
                path('votes/', views.UserViews.votes),
                path('edit', views.UserViews.edit)
            ])),
        ])),
        # todo post related views
        path('p/', include([
            path('', views.PostViews.index),
            # todo POST create
            # path('new', views.PostViews.create),
            path('<url>/', include([
                path('', views.PostViews.post),
                path('vote', views.PostViews.vote),
                path('edit', views.PostViews.edit)
            ]))
        ])),
        # todo wikidata related views
        # path('wiki', views.wiki)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    # todo https://docs.djangoproject.com/en/2.2/howto/static-files/ it is not suitable on prod

backend/community/models.py
import datetime
import os

from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.postgres.fields import JSONField
from enum import Enum
from uuid import uuid4
from django.utils.deconstruct import deconstructible
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser



# todo should this function reside here
# todo this function has a reported bug
# def path_and_rename(path):
#     def wrapper(instance, filename):
#         ext = filename.split('.')[-1]
#         # get filename
#         if instance.pk:
#             filename = '{}.{}'.format(instance.pk, ext)
#         else:
#             # set filename as random string
#             filename = '{}.{}'.format(uuid4().hex, ext)
#         # return the whole path to the file
#         return os.path.join(path, filename)
#     return wrapper


@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.path, filename)


path_and_rename = PathAndRename("images")


class DataFieldTypes(Enum):
    str = "string"
    bl = "boolean"
    dec = "decimal"
    fl = "float"
    dur = "duration"
    dt = "dateTime"
    uri = "anyURI"

    @classmethod
    def all(self):
        return self


class User(models.Model):
    username = models.SlugField(
        max_length=100,
        unique=True
    )
    password = models.CharField(
        max_length=200
    )
    email = models.EmailField(
        max_length=200,
        unique=True
    )
    # image_path = models.CharField(
    #     max_length=100,
    #     null=True,
    #     blank=True
    # )
    image = models.ImageField(
        upload_to=path_and_rename,
        blank=True,
        null=True
    )
    date_registered = models.DateTimeField(
        auto_now=True
    )
    is_archived = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.username


class Community(models.Model):
    # todo should we proceed with reddit style naming conventions
    name = models.SlugField(
        max_length=100,
        unique=True
    )
    description = models.TextField(
        max_length=300
    )
    # url = models.CharField(
    #     max_length=100,
    #     unique=True
    # )
    # todo research on audio video image upload on django
    # image_path = models.CharField(
    #     max_length=100,
    #     null=True,
    #     blank=True
    # )
    image = models.ImageField(
        upload_to=path_and_rename,
        blank=True,
        null=True
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.PROTECT
    )
    members = models.ManyToManyField(
        User,
        through='Membership',
        related_name='members'
    )
    date_created = models.DateTimeField(
        auto_now=True
    )
    is_archived = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.name


class Membership(models.Model):
    class Meta:
        unique_together = [['community', 'user']]

    community = models.ForeignKey(
        Community,
        on_delete=models.PROTECT
    )
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='communities'
    )
    date_joined = models.DateTimeField(
        auto_now=True
    )
    is_admin = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.community.name + " : " + self.user.username


class WikidataItem(models.Model):
    item = models.CharField(
        max_length=25
    )
    label = models.CharField(
        max_length=100
    )
    description = models.CharField(
        max_length=200
    )
    # todo this field would hold information from wikidata item
    data = JSONField(
        blank=True,
        null=True
    )

    def __str__(self):
        return self.label


# class DataField(models.Model):
#     name = models.CharField(
#         max_length=50
#     )
#     # todo i should either use enumeration on type or open a new table for type
#     type = models.CharField(
#         max_length=3,
#         choices=[(tag.name, tag.value) for tag in DataFieldTypes]
#     )
#     is_required = models.BooleanField()
#     # todo OneToOne or ManyToOne // should we add more than one tag to a data field
#     wikidata_item = models.ForeignKey(
#         WikidataItem,
#         null=True,
#         blank=True,
#         on_delete=models.PROTECT
#     )
#     creator = models.ForeignKey(
#         User,
#         on_delete=models.PROTECT
#     )
#     community = models.ForeignKey(
#         Community,
#         on_delete=models.PROTECT,
#         related_name='data_fields'
#     )
#
#     def __str__(self):
#         return self.name


class DataType(models.Model):
    name = models.CharField(
        max_length=100
    )
    # todo update class diagram for this property
    description = models.CharField(
        max_length=100
    )
    fields = JSONField(
        blank=True,
        null=True
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.PROTECT
    )
    community = models.ForeignKey(
        Community,
        on_delete=models.PROTECT,
        related_name='data_types'
    )
    date_created = models.DateTimeField(
        auto_now=True
    )
    tags = JSONField(
        blank=True,
        null=True
    )
    is_archived = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.name


class Post(models.Model):
    data_type = models.ForeignKey(
        DataType,
        on_delete=models.PROTECT,
        null=True
    )
    title = models.CharField(
        max_length=100
    )
    body = models.TextField(
        max_length=2000
    )
    # todo user should not give value to url, it is generated by overriding save method of the model
    url = models.SlugField(
        max_length=100,
        unique=True,
        blank=True
    )
    date_created = models.DateTimeField(
        auto_now=True
    )
    # todo these two should come from vote table, right now it is a placeholder
    # added vote model, could not implement it yet
    # these fields will be obsolete when voting implemented
    upvote_count = models.IntegerField()
    downvote_count = models.IntegerField()
    fields = JSONField(
        blank=True,
        null=True
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='user_posts'
    )
    community = models.ForeignKey(
        Community,
        on_delete=models.PROTECT,
        related_name='community_posts'
    )
    is_archived = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.url

    def save(self, *args, **kwargs):
        self.url = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    # def get_upvote_count(self):
    #     return Vote.objects.filter(is_upvote=True).count()
    #
    # def get_downvote_count(self):
    #     return Vote.objects.filter(is_upvote=False).count()


class Vote(models.Model):
    class Meta:
        unique_together = [['post', 'user']]

    post = models.ForeignKey(
        Post,
        on_delete=models.PROTECT
    )
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT
    )
    is_upvote = models.BooleanField()

#
# class DataFieldType(models.Model):
#     name = models.CharField(
#         max_length=30
#     )
#     type = models.CharField(
#         max_length=30
#     )
#
#     def __str__(self):
#         return self.name
#
#
# class WikidataItem(models.Model):
#     item = models.CharField(
#         max_length=25
#     )
#     label = models.CharField(
#         max_length=100
#     )
#     description = models.CharField(
#         max_length=200
#     )
#
#     def __str__(self):
#         return self.label
#
#
# class User(models.Model):
#     username = models.CharField(
#         max_length=50,
#         unique=True
#     )
#     password = models.CharField(
#         max_length=32
#     )
#     email = models.CharField(
#         max_length=100,
#         unique=True
#     )
#     image_path = models.CharField(
#         max_length=100,
#         null=True,
#         blank=True
#     )
#     date_registered = models.DateTimeField(
#         auto_now=True
#     )
#
#     def __str__(self):
#         return self.username
#
#
# class Community(models.Model):
#     name = models.CharField(
#         max_length=100,
#         unique=True
#     )
#     description = models.TextField(
#         max_length=300
#     )
#     # todo should we proceed with reddit style naming conventions
#     url = models.CharField(
#         max_length=100,
#         unique=True
#     )
#     # todo research on audio video image upload on django
#     image_path = models.CharField(
#         max_length=100,
#         null=True,
#         blank=True
#     )
#     creator = models.ForeignKey(
#         User,
#         on_delete=models.PROTECT,
#         related_name="creator"
#     )
#     members = models.ManyToManyField(
#         User,
#         related_name="member"
#     )
#     date_created = models.DateTimeField(
#         auto_now=True
#     )
#
#     def __str__(self):
#         return self.name
#
#
# class DataField(models.Model):
#     name = models.CharField(
#         max_length=50
#     )
#     # todo i should either use enumeration on type or open a new table for type
#     type = models.ForeignKey(
#         DataFieldType,
#         on_delete=models.PROTECT
#     )
#     is_required = models.BooleanField()
#     # todo OneToOne or ManyToOne // should we add more than one tag to a data field
#     wikidata_item = models.ForeignKey(
#         WikidataItem,

backend/community/forms.py
from django import forms

from .models import *
from django.contrib.auth.forms import UserCreationForm

from django import forms

class UserCreateForm(UserCreationForm):
    email = forms.CharField(required=True)
    image = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ("username", "email","image", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.image = self.cleaned_data["image"]
        if commit:
            user.save()
        return user


class CommunityForm(forms.ModelForm):
    class Meta:
        model = Community
        fields = '__all__'


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','password','email','image']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'


class DataTypeForm(forms.ModelForm):
    class Meta:
        model = DataType
        fields = '__all__'

backend/community/templates/community/basic_search.html
{% extends 'community/layout.html' %}
{% load static %}
{% block content %}
    <h2>Search results for {{ query }}</h2>
    <table>
        {% if 'communities' in data %}
            {% for community in data.communities %}
                <tr>
                    <th colspan="1" width="100px">
                        <label>Community:</label>
                    </th>
                    {% if community.image == null %}
                        <td colspan="4">
                            {% else %}
                        <td colspan="2">
                    {% endif %}
                    <a href="/c/{{ community.name }}">{{ community.name }}</a>
                    </td>
                    {% if community.image != null %}
                        <td colspan="2">
                            <img src="{{ community.image }}" alt="{{ community.name }}" width="600px">
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        {% endif %}
        {% if 'posts' in data %}
            {% for post in data.posts %}
                <tr>
                    <th colspan="1" width="100px">
                        <label>Post:</label>
                    </th>
                    <td colspan="4">
                        <a href="/p/{{ post.url }}">{{ post.title }}</a>
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
        {% if 'users' in data %}
            {% for user in data.users %}
                <tr>
                    <th colspan="1" width="100px">
                        <label>User:</label>
                    </th>
                    <td colspan="2">
                        <a href="/u/{{ user.username }}">{{ user.username }}</a>
                    </td>
                    {% if user.image != null %}
                        <td colspan="2">
                            <img src="{{ user.image }}" alt="{{ user.username }}" width="600px">
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        {% endif %}
    </table>
{% endblock %}

{% block scripts %}
    <script src="{% static 'assets/js/communities.js' %}"></script>
{% endblock %}

backend/community/templates/community/communities.html
{% extends 'community/layout.html' %}
{% load static %}
{% block content %}
{% for community in communities %}
    {% include 'community/partials/community_card.html' with community=community request=request %}
{% endfor %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'assets/js/communities.js' %}"></script>
{% endblock %}

backend/community/templates/community/edit_post.html
{% extends 'community/layout.html' %}
{% load static %}
{% block content %}
    <h2>Edit post: {{ post.title }}</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        <table>
            <tr>
                <th colspan="1">
                    <label for="id_body">Body:</label>
                </th>
                <td colspan="5">
                    <textarea name="body" cols="40" rows="10" maxlength="2000" required id="id_body">{{ post.body }}</textarea>
                </td>
            </tr>
            {% include 'community/partials/post_fields_form.html' with fields=post.fields only %}
            <tr id="button_row">
                <td colspan="6">
                    <button type="submit" class="save btn btn-default fit">Save</button>
                <td>
            </tr>
        </table>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'assets/js/communities.js' %}"></script>
{% endblock %}

backend/community/templates/community/edit_user.html
{% extends 'community/layout.html' %}
{% load static %}
{% block content %}
    <section>
        <h2>Edit User: {{ user.username }}</h2>
        <div class="row gtr-200">
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="row gtr-uniform">
                    <div class="col-6 col-12-xsmall" style="align-content: center;">
                        <label for="email-input">Email:</label>
                        <input type="text" name="email" maxlength="100" autofocus required id="email-input" value="{{ user.email }}">
                    </div>
                    {% if user.image %}
                        <img src="{{ user.image }}" width="500px">
                    {% endif %}
                    <div class="col-6 col-12-xsmall" style="align-content: center;">
                        <label for="image-input">Profile Image:</label>
                        <input type="file" name="image" accept="image/*" id="image-input">
                    </div>
                    <div class="col-12 col-12-xsmall" style="align-content: center;">
                        <button type="submit" class="button primary fit">Edit</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

backend/community/templates/community/header.html
{% load static %}
{#todo user info and other stuff should be here#}
<header id="header">
    <a href="/" class="logo"><strong>CC</strong></a>
    {% if 'current_community' in request.session %}
        <a href="/c/{{ request.session.current_community }}" class="logo" style="text-align: right;">Return to {{ request.session.current_community }}</a>
    {% endif %}
{#    <ul class="icons">#}
{#        <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>#}
{#        <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>#}
{#        <li><a href="#" class="icon brands fa-snapchat-ghost"><span class="label">Snapchat</span></a></li>#}
{#        <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>#}
{#        <li><a href="#" class="icon brands fa-medium-m"><span class="label">Medium</span></a></li>#}
{#    </ul>#}
</header>

backend/community/templates/community/index.html
{% extends 'community/layout.html' %}

backend/community/templates/community/login.html
{% extends 'community/layout.html' %}
{% load static %}
{% block content %}
    <section>
        <h2>Login</h2>
        <div class="row gtr-200">
            <form method="post" action="/u/login">
                {% csrf_token %}
                <div class="row gtr-uniform">
                    <div class="col-6 col-12-xsmall" style="align-content: center;">
                        <label for="username-input">Username:</label>
                        <input type="text" name="username" id="username-input" value="" placeholder="Username">
                    </div>
                    <div class="col-6 col-12-xsmall" style="align-content: center;">
                        <label for="password-input">Password:</label>
                        <input type="password" name="password" id="password-input" value="" placeholder="Password">
                    </div>
                    <div class="col-6 col-12-xsmall" style="align-content: center;">
                        <button type="submit" class="button primary fit">Login</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

backend/community/templates/community/new_datatype.html
{% extends 'community/layout.html' %}
{% load static %}
{% block content %}
    <h2>New datatype</h2>
    <form method="POST" class="post-form" id="create_datatype" action="../datatypes/">
        {% csrf_token %}
        <table>
            <input type="hidden" id="has_fields" name="has_fields" value="0">
            <tr>
                <th colspan="1" width="25px;"><label for="id_name">Name:</label></th>
                <td colspan="5"><input type="text" name="name" maxlength="100" required id="id_name"></td>
            </tr>
            <tr>
                <th colspan="1"><label for="id_description">Description:</label></th>
                <td colspan="5"><input type="text" name="description" maxlength="100" required id="id_description"></td>
            </tr>
            <tr id="button_row">
                <td colspan="6">
                    <button type="button" onclick="addDataFieldRow();" class="button fit">Add Field</button>
                    <button type="submit" class="button primary fit">Save</button>
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'assets/js/communities.js' %}"></script>
{% endblock %}

backend/community/templates/community/new_post.html
{% extends 'community/layout.html' %}
{% load static %}
{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        <table>
        {% include 'community/partials/data_type_selector.html' with data_types=data_types request=request %}
            <tr>
                <th colspan="1">
                    <label for="id_title">Title:</label>
                </th>
                <td colspan="5">
                    <input type="text" name="title" maxlength="100" required id="id_title">
                </td>
            </tr>
            <tr>
                <th colspan="1">
                    <label for="id_body">Body:</label>
                </th>
                <td colspan="5">
                    <textarea name="body" cols="40" rows="10" maxlength="2000" required id="id_body"></textarea>
                </td>
            </tr>
            <tr id="button_row">
                <td colspan="6">
                    <button type="submit" class="save btn btn-default fit">Save</button>
                <td>
            </tr>
        </table>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'assets/js/communities.js' %}"></script>
{% endblock %}

backend/community/templates/community/search_form.html
{% extends 'community/layout.html' %}
{% load static %}
{% block content %}
    <h2>Search on {{ community_name }}</h2>
    <form method="POST" class="post-form">
        {% csrf_token %}
        <table>
        {% include 'community/partials/data_type_selector.html' with data_types=data_types request=request %}
            <tr>
                <th colspan="1">
                    <label for="id_title">Title:</label>
                </th>
                <td colspan="5">
                    <input type="text" name="title" maxlength="100" id="id_title">
                </td>
            </tr>
            <tr>
                <th colspan="1">
                    <label for="id_body">Body:</label>
                </th>
                <td colspan="5">
                    <textarea name="body" cols="40" rows="10" maxlength="2000" id="id_body"></textarea>
                </td>
            </tr>
            <tr id="button_row">
                <td colspan="6">
                    <button type="submit" class="save btn btn-default fit" formnovalidate>Search</button>
                <td>
            </tr>
        </table>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'assets/js/communities.js' %}"></script>
{% endblock %}

backend/community/templates/community/signup.html
{% extends 'community/layout.html' %}
{% load static %}
{% block content %}
    <section>
        <h2>Signup</h2>
        <div class="row gtr-200">
            <form enctype="multipart/form-data" method="post" action="/u/signup">
                {% csrf_token %}
                <div class="row gtr-uniform">
                    <div class="col-6 col-12-xsmall" style="align-content: center;">
                        <label for="email-input">Username:</label>
                        <input type="text" name="username" maxlength="100" autofocus required id="username-input">
                    </div>
                    <div class="col-6 col-12-xsmall" style="align-content: center;">
                        <label for="password-input">Password:</label>
                        <input type="password" name="password" id="password-input" value="" placeholder="Password">
                    </div>
                    <div class="col-6 col-12-xsmall" style="align-content: center;">
                        <label for="email-input">Email:</label>
                        <input type="text" name="email" maxlength="100" autofocus required id="email-input">
                    </div>
                    <div class="col-6 col-12-xsmall" style="align-content: center;">
                        <label for="image-input">Profile Image:</label>
                        <input type="file" name="image" accept="image/*" id="image-input">
                    </div>
                    <div class="col-12 col-12-xsmall" style="align-content: center;">
                        <button type="submit" class="button primary fit">Signup</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

backend/community/templates/community/sparql_results.html
{% extends 'community/layout.html' %}
{% load static %}
{% load community_extras %}
{% block content %}
    <h2>Search results for {{ query }}</h2>
    <table id="sparql_results">
        {% for wikidata in data.results.bindings %}
            {% with wikidata.item.value|get_url:"/" as wikidata_itemId%}
            <tr>
                <th colspan="1" width="100px">
                    <label>{{ wikidata.itemLabel.value }}:</label>
                </th>
                <td colspan="2">
                    <a href="{{ wikidata.item.value }}">{{ wikidata_itemId }}</a>
                </td>
                <td colspan="2">
                    {{ wikidata.itemDescription.value }}
                </td>
            </tr>
            {% endwith %}
        {% endfor %}
    </table>
{% endblock %}

{% block scripts %}
    <script src="{% static 'assets/js/communities.js' %}"></script>
{% endblock %}

backend/community/templates/community/view_community.html
{% extends 'community/layout.html' %}
{% load static %}
{% block content %}
    <section id="banner">
        <div class="content">
            <header>
                <h1>{{ community.name }}</h1>
            </header>
            <p>
                {{ community.description }}
            </p>
            <ul class="actions">
                {% if request.session.username in community.members %}
                    <li><a id="subscribe_{{ community.name }}" onclick="unsubscribe('{{ community.name }}');"
                           class="button big">Unsubscribe</a></li>
                    <li><a id="datatype_{{ community.name }}" href="/c/{{ community.name }}/datatypes/new"
                           class="button big">Create Datatype</a></li>
                    <li><a id="post_{{ community.name }}" href="/c/{{ community.name }}/posts/new" class="button big">Create
                        Post</a></li>
                {% else %}
                    <li><a id="subscribe_{{ community.name }}" onclick="subscribe('{{ community.name }}');"
                           class="button big">Subscribe</a></li>
                {% endif %}
                <li><a id="search_{{ community.name }}" href="search"
                       class="button big">Search in community</a></li>
            </ul>
        </div>
        {% if community.image != null %}
            <span class="image object">
        <img src="{{ community.image }}" alt="{{ community.name }}" height="400px">
    </span>
        {% endif %}
    </section>
    <section>
        <div class="row">
            {% for post in community.community_posts %}
                {% if post.data_type == null %}
                    {% include 'community/partials/generic_post.html' with post=post request=request %}
                {% else %}
                    {% include 'community/partials/post.html' with post=post request=request %}
                {% endif %}
                <hr/>
            {% endfor %}
        </div>
    </section>
{% endblock %}

{% block scripts %}
    <script src="{% static 'assets/js/communities.js' %}"></script>
{% endblock %}