backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('community.urls')),
    path('admin/', admin.site.urls)
]

backend/community/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

# urlpatterns = \
#     [
#         path('login', views.login),
#         path('c/<name>/', include([
#             path('', views.getCommunity),
#             path('members/', views.getCommunityMembers),
#             path('datatypes/', views.getCommunityDataTypes),
#             path('datafields/', views.getCommunityDataFields),
#             path('posts/', views.getCommunityPosts),
#         ])),
#         path('u/<username>/', include([
#             path('', views.getUser),
#         ])),
#         path('p/<url>/', include([
#             path('', views.getPost),
#         ])),
#         path('wiki', views.wiki)
#     ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = \
    [
        # todo homepage
        path('', views.index),
        path('fieldform', views.get_field_form),
        path('postfieldsform', views.get_post_fields_form),
        path('search', views.search),
        path('sparql', views.sparql_query),
        # todo community related views
        path('c/', include([
            path('', views.CommunityViews.index),
            path('new', views.CommunityViews.create),
            path('<name>/', include([
                path('', views.CommunityViews.community),
                path('search', views.CommunityViews.search),
                path('search_results', views.CommunityViews.search_results),
                path('members/', views.CommunityViews.members),
                path('datatypes/', include([
                    path('', views.CommunityViews.data_types),
                    path('new', views.DataTypeViews.create)
                ])),
                path('posts/', include([
                    path('', views.CommunityViews.posts),
                    path('new', views.PostViews.create)
                ]))
            ]))
        ])),
        # todo user related views
        path('u/', include([
            path('', views.UserViews.index),
            # todo GET loginform?, POST login
            path('login', views.UserViews.login),
            path('logout', views.UserViews.logout),
            # todo GET signupform?, POST signup
            path('signup', views.UserViews.signup),
            path('<username>/', include([
                path('', views.UserViews.user),
                path('datatypes/', views.UserViews.data_types),
                path('datatype/<id>', views.UserViews.data_type),
                path('posts/', views.UserViews.posts),
                path('votes/', views.UserViews.votes),
                path('edit', views.UserViews.edit)
            ])),
        ])),
        # todo post related views
        path('p/', include([
            path('', views.PostViews.index),
            # todo POST create
            # path('new', views.PostViews.create),
            path('<url>/', include([
                path('', views.PostViews.post),
                path('vote', views.PostViews.vote),
                path('edit', views.PostViews.edit)
            ]))
        ])),
        # todo wikidata related views
        # path('wiki', views.wiki)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    # todo https://docs.djangoproject.com/en/2.2/howto/static-files/ it is not suitable on prod

backend/community/models.py
import datetime
import os

from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.postgres.fields import JSONField
from enum import Enum
from uuid import uuid4
from django.utils.deconstruct import deconstructible
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser



# todo should this function reside here
# todo this function has a reported bug
# def path_and_rename(path):
#     def wrapper(instance, filename):
#         ext = filename.split('.')[-1]
#         # get filename
#         if instance.pk:
#             filename = '{}.{}'.format(instance.pk, ext)
#         else:
#             # set filename as random string
#             filename = '{}.{}'.format(uuid4().hex, ext)
#         # return the whole path to the file
#         return os.path.join(path, filename)
#     return wrapper


@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(self.path, filename)


path_and_rename = PathAndRename("images")


class DataFieldTypes(Enum):
    str = "string"
    bl = "boolean"
    dec = "decimal"
    fl = "float"
    dur = "duration"
    dt = "dateTime"
    uri = "anyURI"

    @classmethod
    def all(self):
        return self


class User(models.Model):
    username = models.SlugField(
        max_length=100,
        unique=True
    )
    password = models.CharField(
        max_length=200
    )
    email = models.EmailField(
        max_length=200,
        unique=True
    )
    # image_path = models.CharField(
    #     max_length=100,
    #     null=True,
    #     blank=True
    # )
    image = models.ImageField(
        upload_to=path_and_rename,
        blank=True,
        null=True
    )
    date_registered = models.DateTimeField(
        auto_now=True
    )
    is_archived = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.username


class Community(models.Model):
    # todo should we proceed with reddit style naming conventions
    name = models.SlugField(
        max_length=100,
        unique=True
    )
    description = models.TextField(
        max_length=300
    )
    # url = models.CharField(
    #     max_length=100,
    #     unique=True
    # )
    # todo research on audio video image upload on django
    # image_path = models.CharField(
    #     max_length=100,
    #     null=True,
    #     blank=True
    # )
    image = models.ImageField(
        upload_to=path_and_rename,
        blank=True,
        null=True
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.PROTECT
    )
    members = models.ManyToManyField(
        User,
        through='Membership',
        related_name='members'
    )
    date_created = models.DateTimeField(
        auto_now=True
    )
    is_archived = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.name


class Membership(models.Model):
    class Meta:
        unique_together = [['community', 'user']]

    community = models.ForeignKey(
        Community,
        on_delete=models.PROTECT
    )
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='communities'
    )
    date_joined = models.DateTimeField(
        auto_now=True
    )
    is_admin = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.community.name + " : " + self.user.username


class WikidataItem(models.Model):
    item = models.CharField(
        max_length=25
    )
    label = models.CharField(
        max_length=100
    )
    description = models.CharField(
        max_length=200
    )
    # todo this field would hold information from wikidata item
    data = JSONField(
        blank=True,
        null=True
    )

    def __str__(self):
        return self.label


# class DataField(models.Model):
#     name = models.CharField(
#         max_length=50
#     )
#     # todo i should either use enumeration on type or open a new table for type
#     type = models.CharField(
#         max_length=3,
#         choices=[(tag.name, tag.value) for tag in DataFieldTypes]
#     )
#     is_required = models.BooleanField()
#     # todo OneToOne or ManyToOne // should we add more than one tag to a data field
#     wikidata_item = models.ForeignKey(
#         WikidataItem,
#         null=True,
#         blank=True,
#         on_delete=models.PROTECT
#     )
#     creator = models.ForeignKey(
#         User,
#         on_delete=models.PROTECT
#     )
#     community = models.ForeignKey(
#         Community,
#         on_delete=models.PROTECT,
#         related_name='data_fields'
#     )
#
#     def __str__(self):
#         return self.name


class DataType(models.Model):
    name = models.CharField(
        max_length=100
    )
    # todo update class diagram for this property
    description = models.CharField(
        max_length=100
    )
    fields = JSONField(
        blank=True,
        null=True
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.PROTECT
    )
    community = models.ForeignKey(
        Community,
        on_delete=models.PROTECT,
        related_name='data_types'
    )
    date_created = models.DateTimeField(
        auto_now=True
    )
    tags = JSONField(
        blank=True,
        null=True
    )
    is_archived = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.name


class Post(models.Model):
    data_type = models.ForeignKey(
        DataType,
        on_delete=models.PROTECT,
        null=True
    )
    title = models.CharField(
        max_length=100
    )
    body = models.TextField(
        max_length=2000
    )
    # todo user should not give value to url, it is generated by overriding save method of the model
    url = models.SlugField(
        max_length=100,
        unique=True,
        blank=True
    )
    date_created = models.DateTimeField(
        auto_now=True
    )
    # todo these two should come from vote table, right now it is a placeholder
    # added vote model, could not implement it yet
    # these fields will be obsolete when voting implemented
    upvote_count = models.IntegerField()
    downvote_count = models.IntegerField()
    fields = JSONField(
        blank=True,
        null=True
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='user_posts'
    )
    community = models.ForeignKey(
        Community,
        on_delete=models.PROTECT,
        related_name='community_posts'
    )
    is_archived = models.BooleanField(
        default=False
    )

    def __str__(self):
        return self.url

    def save(self, *args, **kwargs):
        self.url = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    # def get_upvote_count(self):
    #     return Vote.objects.filter(is_upvote=True).count()
    #
    # def get_downvote_count(self):
    #     return Vote.objects.filter(is_upvote=False).count()


class Vote(models.Model):
    class Meta:
        unique_together = [['post', 'user']]

    post = models.ForeignKey(
        Post,
        on_delete=models.PROTECT
    )
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT
    )
    is_upvote = models.BooleanField()

#
# class DataFieldType(models.Model):
#     name = models.CharField(
#         max_length=30
#     )
#     type = models.CharField(
#         max_length=30
#     )
#
#     def __str__(self):
#         return self.name
#
#
# class WikidataItem(models.Model):
#     item = models.CharField(
#         max_length=25
#     )
#     label = models.CharField(
#         max_length=100
#     )
#     description = models.CharField(
#         max_length=200
#     )
#
#     def __str__(self):
#         return self.label
#
#
# class User(models.Model):
#     username = models.CharField(
#         max_length=50,
#         unique=True
#     )
#     password = models.CharField(
#         max_length=32
#     )
#     email = models.CharField(
#         max_length=100,
#         unique=True
#     )
#     image_path = models.CharField(
#         max_length=100,
#         null=True,
#         blank=True
#     )
#     date_registered = models.DateTimeField(
#         auto_now=True
#     )
#
#     def __str__(self):
#         return self.username
#
#
# class Community(models.Model):
#     name = models.CharField(
#         max_length=100,
#         unique=True
#     )
#     description = models.TextField(
#         max_length=300
#     )
#     # todo should we proceed with reddit style naming conventions
#     url = models.CharField(
#         max_length=100,
#         unique=True
#     )
#     # todo research on audio video image upload on django
#     image_path = models.CharField(
#         max_length=100,
#         null=True,
#         blank=True
#     )
#     creator = models.ForeignKey(
#         User,
#         on_delete=models.PROTECT,
#         related_name="creator"
#     )
#     members = models.ManyToManyField(
#         User,
#         related_name="member"
#     )
#     date_created = models.DateTimeField(
#         auto_now=True
#     )
#
#     def __str__(self):
#         return self.name
#
#
# class DataField(models.Model):
#     name = models.CharField(
#         max_length=50
#     )
#     # todo i should either use enumeration on type or open a new table for type
#     type = models.ForeignKey(
#         DataFieldType,
#         on_delete=models.PROTECT
#     )
#     is_required = models.BooleanField()
#     # todo OneToOne or ManyToOne // should we add more than one tag to a data field
#     wikidata_item = models.ForeignKey(
#         WikidataItem,

backend/community/forms.py
from django import forms

from .models import *
from django.contrib.auth.forms import UserCreationForm

from django import forms

class UserCreateForm(UserCreationForm):
    email = forms.CharField(required=True)
    image = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ("username", "email","image", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.image = self.cleaned_data["image"]
        if commit:
            user.save()
        return user


class CommunityForm(forms.ModelForm):
    class Meta:
        model = Community
        fields = '__all__'


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','password','email','image']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'


class DataTypeForm(forms.ModelForm):
    class Meta:
        model = DataType
        fields = '__all__'

backend/community/templates/community/partials/community_card.html
{% load static %}
<section id="banner">
    <div class="content">
        <header>
            <h1>{{ community.name }}</h1>
        </header>
        <p>
            {{ community.description }}
        </p>
        <ul class="actions">
            <li><a href="/c/{{ community.name }}" class="button big">Take a look!</a></li>
{#            {% if request.session.username in community.members %}#}
{#                <li><a id="subscribe_{{ community.name }}" onclick="unsubscribe('{{ community.name }}');" class="button big">Unsubscribe</a></li>#}
{#            {% else %}#}
{#                <li><a id="subscribe_{{ community.name }}" onclick="subscribe('{{ community.name }}');" class="button big">Subscribe</a></li>#}
{#            {% endif %}#}
        </ul>
    </div>
{% if community.image != null %}
    <span class="image object">
        <img src="{{ community.image }}" alt="{{ community.name }}">
    </span>
{% endif %}
</section>

backend/community/templates/community/partials/data_type_selector.html
{% load static %}
<tr>
    <th colspan="1" width="120px"><label for="id_data_type">DataType:</label></th>
    <td colspan="5">
        <select onchange="getDataFields(this)" name="data_type" id="id_data_type">
            <option value="" selected>Generic Post</option>
            {% for data_type in data_types %}
                <option value="{{ data_type.id }}">{{ data_type.name }}</option>
            {% endfor %}
        </select>
    </td>
</tr>

{#{% for data_type in data_types %}#}
{#    {% with data_type.id|slugify as id %}#}
{#        {% with "dt_"|add:id as name %}#}
{#            {{ data_type.fields|json_script:name }}#}
{#        {% endwith %}#}
{#    {% endwith %}#}
{#{% endfor %}#}

backend/community/templates/community/partials/field_form.html
{% load static %}
<tr id="data_field_{{ index }}">
    <th colspan="1">
        <label for="id_field_label_{{ index }}">Label:</label>
    </th>
    <td colspan="1">
        <input type="text" name="field_label_{{ index }}" maxlength="100" required id="id_field_label_{{ index }}">
    </td>
    <th colspan="1">
        <label for="id_field_type_{{ index }}">Type:</label>
    </th>
    <td colspan="1">
        <select onchange="enableChoices(this)" name="field_type_{{ index }}" required id="id_field_type_{{ index }}" data-id="{{ index }}">
            <option value="" selected>Select a type</option>
            <option value="string">string</option>
            <option value="textarea">textarea</option>
            <option value="integer">integer</option>
            <option value="float">float</option>
            <option value="boolean">boolean</option>
            <option value="image">image</option>
            <option value="audio">audio</option>
            <option value="video">video</option>
            <option value="uri">uri</option>
            <option value="datetime">datetime</option>
            <option value="date">date</option>
            <option value="time">time</option>
            <option value="list">list</option>
            <option value="enumeration">enumeration</option>
            <option value="multiple">multiple choice</option>
            <option value="geolocation">geolocation</option>
        </select>
    </td>
    <td colspan="1">
        <input type="checkbox" id="id_is_required_{{ index }}" name="is_required_{{ index }}">
        <label for="id_is_required_{{ index }}">Is required</label>
    </td>
    <td colspan="1">
        <button type="button" class="button primary small icon solid fa-trash" onclick="deleteDataFieldRow(this)" data-id="{{ index }}"></button>
    </td>
</tr>
<tr id="choice_{{ index }}" style="display: none;">
    <th colspan="1">
        <label for="id_choice_values_{{ index }}">Choices:</label>
    </th>
    <td colspan="5">
    <textarea  name="choice_values_{{ index }}" id="id_choice_values_{{ index }}"></textarea>
    </td>
</tr>

backend/community/templates/community/partials/generic_post.html
{% load static %}
<div class="col-6 col-12-small">
    <h3><a href="/p/{{ post.url }}">{{ post.title }}</a></h3>
    <p>{{ post.body }}</p>
</div>

backend/community/templates/community/partials/post.html
{% load static %}
<div>
    <h3><a href="/p/{{ post.url }}">{{ post.title }}</a></h3>
    <p>{{ post.body }}</p>
</div>
<table>
    {% for field in post.fields %}
        {% with "community/partials/post_fields/"|add:field.type as field_tpye %}
            {% with field_tpye|add:'.html' as field_template %}
                {% include field_template with field=field only %}
            {% endwith %}
        {% endwith %}
    {% endfor %}
</table>

backend/community/templates/community/partials/post_fields_form.html
{% load static %}
{% for field in fields %}
    {% with "community/partials/input_fields/"|add:field.type as field_tpye %}
        {% with field_tpye|add:'.html' as field_template %}
            {% include field_template with field=field only %}
        {% endwith %}
    {% endwith %}
{% endfor %}